config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  # root 'home#index'
  root 'friends#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
    validates :first_name, :email, :phone, :address, presence: true
    validates :first_name, length: {minimum:2, maximum:50}
    validates :first_name, format: {with: /\A[a-zA-Z]+\z/, message: "- Only letters allowed in name"}
    validates :phone, numericality: true, length: {minimum:10, maximum:12}
    validates :email, format: Devise.email_regexp
    validates :address, length: {minimum:4, maximum:50}
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]
         has_many :friend
         validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
         validates :username, presence: true, uniqueness: { case_sensitive: false }
         validate :validate_username



  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friend.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friend.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friend.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :address, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My name is test programmer"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(path)
        if request.path == path
          return 'active'
        else
          return ''
        end
      end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, data: {turbo: false}) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <%
=begin%>
 <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2> 
<%
=end%>

      <%
=begin%>
 <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul> 
<%
=end%>

          <% is_first_name_invalid =  friend.errors.include?(:first_name) %> 
          <% is_email_invalid = friend.errors.include?(:email) %>
          <% is_phone_invalid = friend.errors.include?(:phone) %> 
          <% is_address_invalide = friend.errors.include?(:address) %>
    </div>
  <% end %>

  <div class="form-row">
    <div class="col-md-6 mb-3">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class:"form-control #{'is-invalid' if is_first_name_invalid}", :required=> true %>
      <% if is_first_name_invalid %>
          <div class="invalid-feedback d-block">
            <% friend.errors.full_messages_for(:first_name).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </div>
       <% end %>
    </div>
    <div class="col-md-6 mb-3">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control  #{'is-invalid' if is_email_invalid}", placeholder:"name@email.com", :required=> true %>
    <% if is_email_invalid %>
          <div class="invalid-feedback d-block">
            <% friend.errors.full_messages_for(:email).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </div>
       <% end %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control #{'is-invalid' if is_phone_invalid}", placeholder:"123-456-7890", :required=> true %>
    <% if is_phone_invalid %>
          <div class="invalid-feedback d-block">
            <% friend.errors.full_messages_for(:phone).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </div>
       <% end %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class:"form-control #{'is-invalid' if is_address_invalide}", placeholder:"Address", :required=> true %>
    <% if is_address_invalide %>
          <div class="invalid-feedback d-block">
            <% friend.errors.full_messages_for(:address).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </div>
       <% end %>
  </div>

   <div class="form-group">
    <%= form.text_field :user_id,id: :friend_user_id,  class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary" %>
    
  </div>
<% end %>

app/views/friends/_friend.html.erb
<% @id += 1 %>
<tr id="<%= dom_id friend %>">
      <th scope="row"><%= @id %></th>
      <td> 
      <% name = friend.first_name + " " + friend.last_name %>
      <%= link_to name, friend, class:"btn btn-link pt-0 pb-2 text-dark" %></td>

      <td> <%= friend.email %></td>
      <td> <%= friend.phone %></td>
      <td> <%= friend.address %></td>
      <%
=begin%>
 <td> <%= friend.user_id %></td> 
<%
=end%>
      <td class="d-flex flex-row"> 
    

          <%
=begin%>
 <%= link_to "Show", friend, class:"btn btn-outline-info btn-sm  " %> 

          <%= link_to "Edit", edit_friend_path(friend), class:"btn btn-outline-secondary btn-sm ml-2" %> 
<%
=end%>
          <%= button_to "Delete", friend, method: :delete, class:"btn btn-outline-danger btn-sm ml-2" %>
      </td>
</tr>

app/views/friends/edit.html.erb
<h1 class="mt-4 mb-3">Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <div class="d-flex flex-column">
    <div class="d-flex flex-row">
        <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %>
        <%= button_to "Delete Friend", @friend, method: :delete, class:"btn btn-danger ml-3" %>
    </div>
    <div class="mt-2">
        <%= link_to "Back to friends", friends_path, class:"btn btn-dark"  %>
    </div>
  </div>
  
</div>

app/views/friends/index.html.erb
<%
=begin%>
 <p style="color: green"><%= notice %></p> 
<%
=end%>
<% if user_signed_in?%>
<h1>Friends List</h1>

<div id="friends">
<table class="table table-hover table-striped  table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <%
=begin%>
 <th scope="col">Last Name</th> 
<%
=end%>
      <th scope="col">Email</th>
      <th scope="col">Phone number</th>
      <th scope="col">Address</th>
      <%
=begin%>
 <th scope="col">Created By</th>    
<%
=end%>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @id = 0%>
    <% @friends.each do |friend| %>
    <% if friend.user == current_user %>
    <%= render friend %>
    <% end %>
    <%
=begin%>
 <p>
      <%= link_to "Show this friend", friend %>
    </p> 
<%
=end%>
  <% end %>

  </tbody>
</table>
</div>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

<% else %>
<%= render :template => 'home/index'  %>
<% end %>

app/views/friends/new.html.erb
<h1 class="mt-3 mb-4">Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<%
=begin%>
 <p style="color: green"><%= notice %></p> 
<%
=end%>

<div class="jumbotron">
  <h1 class="display-4">
      Hello,
  </h1>
  <h1 class="display-5">
    <%= @friend.first_name %> <%= @friend.last_name %>
  </h1>
  <p class="lead"><%= @friend.email %> | <%= @friend.phone %> </p>
  <hr class="my-2">
  <p><%= @friend.address %></p>
    
    <div class="d-flex flex-row">
    <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-dark" %>
    <%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-danger ml-3" %>
    </div>
</div>
<%


=begin%>
 
<%= render @friend %> 
<%
=end%>

<div>
<%= link_to "Back to friends", friends_path, class:"btn btn-secondary ml-2" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'Task app', root_path,class: "navbar-brand"  %>
  <%
=begin%>
 <a class="navbar-brand" href="#">Task app</a> 
<%
=end%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    <% if user_signed_in? %>
      <li class="nav-item <%= active_class(friends_path) %>">
          <%= link_to "Show Friends", friends_path, class: "nav-link" %>
      </li>
     <% end %> 
    
      <%
=begin%>
 <li class="nav-item">
      <%= link_to "Home", home_index_path, class: "nav-link active" %> 
<%
=end%>
<%
=begin%>
 <a class="nav-link active" href="#">Home</a> 
<%
=end%>
      </li>
      <li class="nav-item <%= active_class(home_about_path) %>">
      <%= link_to "About", home_about_path, class: "nav-link" %>
        <%
=begin%>
 <a class="nav-link " href="#">About</a> 
<%
=end%>
      </li>

    </ul>
    <%
=begin%>
 <% if user_signed_in? %>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    <% end %>  
<%
=end%>
    <div>
      <ul class="navbar-nav my-2 my-lg-0">
      <% if user_signed_in? %>
          <span class="navbar-text ml-3">
              Hi, <%= current_user.email %>
          </span>
          <li class="nav-item <%= active_class(edit_user_registration_path) %>">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

      <% else %>
          <li class="nav-item <%= active_class(new_user_registration_path) %>">
              <%= link_to "Sign Up",  new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= active_class(new_user_session_path) %>">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
      <% end %>          
      </ul>
    </div>
    
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us... </h1>

<p>
    <%= @about_me %>
</p>

app/views/home/index.html.erb
<h1>Hello World</h1>

<p>This is my first Rails page<p>

app/views/layouts/_alert.html.erb
<div class="alert alert-danger alert-dismissible fade show" role="alert">
 <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <title>Blog</title>
  </head>
  <body>
  <header>
    <%= render 'home/header' %>
        <% if notice %>
            <%= render "layouts/alerts" %>
        <% end %>
        <% if alert %>
            <%= render "layouts/alert" %>
        <% end %>
  </header>
  <div class="container">
        <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>